print-config: true
# Replica Info
replica-info:
  replica-ips:
    - 10.128.2.10
    - 10.128.2.11
    - 10.128.2.12
  receiver-shards: 2 # The number of threads to receive threads
  receiver-port: 33333 # The port is exposed to client/proxy and is used to receive client/proxy requests. When receiver-shards>1, the corresponding ports are receiver-ports + shard-index
  initial-owd: 80 # The initial one-way delay (us) between replicas and proxies
# Proxy Info
proxy-info:
  endpoint-type: 1 # 1 for UDP Endpoint, 2 for GRPC Endpoint [to be supported soon]
  proxy-id: 2
  proxy-ip: 10.128.2.24
  shard-num: 12
  max-owd: 200
  request-port-base: 32000
  reply-port-base: 33000
