# Bazel action to build & test specific targets.
name: Bazel build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Bazel build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bazel
        run: |
          sudo apt install -y apt-transport-https curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update
          sudo apt install -y bazel-5.2.0
          sudo mv /usr/bin/bazel-5.2.0 /usr/bin/bazel

      - name: Build
        run: |
          bazel build //replica/... //proxy/... //client/...
  local-test:
    name: Run local test
    runs-on: ubuntu-20.04
    steps:
      - name: Run local test
        run: ./scripts/local_test.sh
